markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://herohunfer.com/blog
author: herohnfer
pygments: true
safe: true
paginate: 16
auto: true
production_url : http://herohunfer.com/blog

